//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket_product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
    
        public virtual User1 User1 { get; set; }
    }
}
