//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public string Product { get; set; }
        public byte Count { get; set; }
        public System.DateTime DataTime { get; set; }
        public int Id { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Services Services { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
