//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Id { get; set; }
        public string type_of { get; set; }
        public string description_of { get; set; }
        public int duration { get; set; }
        public string staff { get; set; }
        public int price { get; set; }
    
        public virtual ProductSale ProductSale { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
