//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int id_user { get; set; }
        public string login_user { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string password_user { get; set; }
        public string name_user { get; set; }
        public string surname_user { get; set; }
        public string patronymic { get; set; }
        public string email_user { get; set; }
        public Nullable<System.DateTime> datetime_user { get; set; }
        public string sex { get; set; }
        public System.DateTime birthday { get; set; }
    
        public virtual Basket_product Basket_product { get; set; }
        public virtual ProductSale ProductSale { get; set; }
    }
}
